"""migracao_inicial

Revision ID: 118bf6db9548
Revises: 2599448d396f
Create Date: 2026-02-11 17:48:49.172640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118bf6db9548'
down_revision: Union[str, Sequence[str], None] = '2599448d396f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('sabor', sa.String(), nullable=True),
    sa.Column('tamanho', sa.String(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=True),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['Pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedidos')
    op.drop_table('Pedido')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
