"""relacoes_bidirecionais e mudancas_tabelas

Revision ID: 1228077e4c6d
Revises: 2c524d548dc7
Create Date: 2026-02-12 18:12:33.741701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1228077e4c6d'
down_revision: Union[str, Sequence[str], None] = '2c524d548dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 🔁 renomeia a tabela
    op.rename_table('Pedido', 'pedidos')

    # 🔁 renomeia coluna pedido -> pedido_id
    op.add_column('itens_pedidos', sa.Column('pedido_id', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE itens_pedidos
        SET pedido_id = pedido
    """)

    op.drop_constraint(op.f('itens_pedidos_pedido_fkey'),
                       'itens_pedidos',
                       type_='foreignkey')

    op.create_foreign_key(
        'itens_pedidos_pedido_id_fkey',
        'itens_pedidos',
        'pedidos',
        ['pedido_id'],
        ['id']
    )

    op.drop_column('itens_pedidos', 'pedido')

    # 💰 altera preco_unitario para Numeric
    op.alter_column(
        'itens_pedidos',
        'preco_unitario',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True
    )





# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('pedidos',
#     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#     sa.Column('status', sa.String(), nullable=True),
#     sa.Column('preco', sa.Float(), nullable=True),
#     sa.Column('criado_em', sa.DateTime(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('Pedido')
#     op.add_column('itens_pedidos', sa.Column('pedido_id', sa.Integer(), nullable=True))
#     op.alter_column('itens_pedidos', 'preco_unitario',
#                existing_type=sa.DOUBLE_PRECISION(precision=53),
#                type_=sa.Numeric(precision=10, scale=2),
#                existing_nullable=True)
#     op.drop_constraint(op.f('itens_pedidos_pedido_fkey'), 'itens_pedidos', type_='foreignkey')
#     op.create_foreign_key(None, 'itens_pedidos', 'pedidos', ['pedido_id'], ['id'])
#     op.drop_column('itens_pedidos', 'pedido')
#     # ### end Alembic commands ###

def downgrade() -> None:
    op.add_column('itens_pedidos',
                  sa.Column('pedido', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE itens_pedidos
        SET pedido = pedido_id
    """)

    op.drop_constraint('itens_pedidos_pedido_id_fkey',
                       'itens_pedidos',
                       type_='foreignkey')

    op.create_foreign_key(
        op.f('itens_pedidos_pedido_fkey'),
        'itens_pedidos',
        'Pedido',
        ['pedido'],
        ['id']
    )

    op.drop_column('itens_pedidos', 'pedido_id')

    op.alter_column(
        'itens_pedidos',
        'preco_unitario',
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True
    )

    op.rename_table('pedidos', 'Pedido')







# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('itens_pedidos', sa.Column('pedido', sa.INTEGER(), autoincrement=False, nullable=True))
#     op.drop_constraint(None, 'itens_pedidos', type_='foreignkey')
#     op.create_foreign_key(op.f('itens_pedidos_pedido_fkey'), 'itens_pedidos', 'Pedido', ['pedido'], ['id'])
#     op.alter_column('itens_pedidos', 'preco_unitario',
#                existing_type=sa.Numeric(precision=10, scale=2),
#                type_=sa.DOUBLE_PRECISION(precision=53),
#                existing_nullable=True)
#     op.drop_column('itens_pedidos', 'pedido_id')
#     op.create_table('Pedido',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('usuario', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['usuario'], ['usuarios.id'], name=op.f('Pedido_usuario_fkey')),
#     sa.PrimaryKeyConstraint('id', name=op.f('Pedido_pkey'))
#     )
#     op.drop_table('pedidos')
#     # ### end Alembic commands ###
